//! Native (pure Rust) bare-metal firmware for the NXP S32K312 (Cortex-M7).
//!
//! Boot flow (see `Reset_Handler`):
//!   1. Disable global interrupts via inline asm (`cpsid i`).
//!   2. Zero r0 via `eor r0, r0, r0` (ARM xor), and read SP for Rust use.
//!   3. Zero 16 bytes at SP-16..SP-1 (two 64-bit volatile writes).
//!   4. Inline-copy memcpy64 from FLASH (LMA) to ITCM (VMA) using a Rust
//!      loop -- cannot call memcpy64 yet because it is not in ITCM.
//!   5. Call memcpy64 to copy the rest of itcm_text (memset64) from FLASH
//!      to ITCM.  Now memcpy64 is in place and callable.
//!   6. Call `main` (never returns).
//!
//! Only step 1+2 use inline asm; the rest is plain Rust.
//!
//! Interrupt handling:
//!   - Full vector table (229 entries: SP + 15 core exceptions +
//!     213 external IRQs up to IRQ212).
//!   - Every handler is a weak alias of `Default_Handler` (infinite loop).
//!   - If a same-named strong handler is defined elsewhere, it overrides.

#![no_std]
#![no_main]

use core::panic::PanicInfo;
use core::ptr;

// MCU peripheral access crate (generated by svd2rust from S32K312_M7.svd).
pub mod mcu;

// Vector table (228 entries: SP + core exceptions + external IRQs).
pub mod vector_table;

// IVT table (256-byte header at FLASH start, MagicNumber = 0x55AA55AA).
pub mod ivt_table;

// =====================================================================
// Reset_Handler -- reset entry point.
//
// The hardware enters here out of reset with SP already loaded from
// VECTOR_TABLE[0]. Only the first two instructions (cpsid i + eor r0)
// are inline asm; the rest is plain Rust. This function never returns.
//
// Boot sequence:
//   1. cpsid i             -- disable global interrupts (asm)
//   2. eor r0, r0, r0      -- zero r0 via xor (asm), read SP into Rust
//   3. Zero 16 bytes at SP-16..SP-1 (Rust volatile writes)
//   4. Inline-copy memcpy64 from FLASH to ITCM (Rust loop, cannot call
//      memcpy64 before it is in place)
//   5. Call memcpy64 to copy itcm_text (memset64) from FLASH to ITCM
//   6. Call main (never returns)
// =====================================================================
#[no_mangle]
#[link_section = ".text.Reset_Handler"]
pub unsafe extern "C" fn Reset_Handler() -> ! {
    // (1) Disable global interrupts.
    // (2) Zero r0 via xor (ARM: eor). Also read SP for use by Rust code.
    let sp: usize;
    core::arch::asm!(
        "cpsid i",
        "eor r0, r0, r0",
        "mov {sp}, sp",
        sp = out(reg) sp,
        out("r0") _,
        options(nostack, nomem),
    );

    // (3) Zero 16 bytes at SP-16..SP-1 (two 8-byte writes).
    let sp_ptr = sp as *mut u64;
    ptr::write_volatile(sp_ptr.offset(-2), 0); // SP-16 .. SP-9
    ptr::write_volatile(sp_ptr.offset(-1), 0); // SP-8  .. SP-1

    // (4) Phase 1: inline-copy memcpy64 itself from FLASH to ITCM.
    //     Cannot call memcpy64 yet -- it is not in ITCM.
    extern "C" {
        static __memcpy64_start: u8;
        static __memcpy64_end: u8;
        static __memcpy64_load: u8;
        static __itcm_text_start: u8;
        static __itcm_text_end: u8;
        static __itcm_text_load: u8;
    }
    let m64_src = ptr::addr_of!(__memcpy64_load);
    let m64_dst = ptr::addr_of!(__memcpy64_start) as *mut u8;
    let m64_len =
        ptr::addr_of!(__memcpy64_end) as usize - ptr::addr_of!(__memcpy64_start) as usize;
    let m64_count = m64_len / 8;
    for i in 0..m64_count {
        let offset = i * 8;
        let s = (m64_src as usize + offset) as *const u64;
        let d = (m64_dst as usize + offset) as *mut u64;
        let val = ptr::read_volatile(s);
        ptr::write_volatile(d, val);
    }

    // (5) Phase 2: memcpy64 is now in ITCM. Call it to copy itcm_text.
    let text_src = ptr::addr_of!(__itcm_text_load);
    let text_dst = ptr::addr_of!(__itcm_text_start) as *mut u8;
    let text_len =
        ptr::addr_of!(__itcm_text_end) as usize - ptr::addr_of!(__itcm_text_start) as usize;
    // Route through black_box to stop LLVM rewriting the call as a memcpy builtin.
    let do_copy: unsafe extern "C" fn(*const u8, *mut u8, usize) -> *mut u8 =
        core::hint::black_box(memcpy64);
    do_copy(text_src, text_dst, text_len);

    // (6) Call main (never returns).
    main();
}

// =====================================================================
// memcpy64 -- self-implemented 8-byte aligned block copy.
//
// Parameter order (per spec): (src, dst, n)
//   src : 起始地址 (start / source address)
//   dst : 目标地址 (target / destination address)
//   n   : 字节数长度 (byte count, must be a multiple of 8)
//
// Caller guarantees src and dst are 8-byte aligned.
//
// Returns dst.
// =====================================================================
#[no_mangle]
#[link_section = ".itcm_text.memcpy64"]
#[inline(never)]
pub unsafe extern "C" fn memcpy64(src: *const u8, dst: *mut u8, n: usize) -> *mut u8 {
    let count = n / 8;
    let mut i: usize = 0;
    while i < count {
        let offset = i * 8;
        let s = (src as usize + offset) as *const u64;
        let d = (dst as usize + offset) as *mut u64;
        let val = ptr::read_volatile(s);
        ptr::write_volatile(d, val);
        i += 1;
    }
    dst
}

// =====================================================================
// memset64 -- 8-byte aligned memory fill with a u64 value.
//
// Parameter order (per spec): (dst, value, n)
//   dst   : target address (must be 8-byte aligned)
//   value : u64 fill value
//   n     : byte count (must be a multiple of 8)
//
// Returns dst.
// =====================================================================
#[no_mangle]
#[link_section = ".itcm_text"]
#[inline(never)]
pub unsafe extern "C" fn memset64(dst: *mut u8, value: u64, n: usize) -> *mut u8 {
    let count = n / 8;
    let mut i: usize = 0;
    while i < count {
        let offset = i * 8;
        let d = (dst as usize + offset) as *mut u64;
        ptr::write_volatile(d, value);
        i += 1;
    }
    dst
}

// =====================================================================
// Default_Handler -- default interrupt handler (infinite loop).
// All undefined interrupt handlers are weak aliases (via PROVIDE in
// link.x) of this function.  A strong definition of any handler
// elsewhere overrides the PROVIDE.
// =====================================================================
#[no_mangle]
#[link_section = ".text.Default_Handler"]
pub extern "C" fn Default_Handler() -> ! {
    loop {}
}

// =====================================================================
// main -- an empty infinite loop (standard Rust fn, no extern "C").
// =====================================================================
#[inline(never)]
fn main() -> ! {
    loop {}
}

// =====================================================================
// Panic handler -- just spin.
// =====================================================================
#[panic_handler]
fn panic(_info: &PanicInfo) -> ! {
    loop {}
}
