//! Native (pure Rust) bare-metal firmware for the NXP S32K312 (Cortex-M7).
//!
//! Boot flow (see `Reset_Handler`):
//!   1. Disable global interrupts via `cortex_m::interrupt::disable`.
//!   2. Copy ramcode (memcpy64 + memset64) from its load address in FLASH
//!      to its link address in ITCM.  Section start/end and load address
//!      are all 8-byte aligned, and the length is a multiple of 8.
//!   3. Call `main`, which is an empty infinite loop.
//!
//! Interrupt handling:
//!   - Full vector table (229 entries: SP + 15 core exceptions +
//!     213 external IRQs up to IRQ212).
//!   - Every handler is a weak alias of `Default_Handler` (infinite loop).
//!   - If a same-named strong handler is defined elsewhere, it overrides.

#![no_std]
#![no_main]

use core::panic::PanicInfo;
use core::ptr;

use cortex_m::interrupt;

// MCU peripheral access crate (generated by svd2rust from S32K312_M7.svd).
pub mod mcu;

// Vector table (228 entries: SP + core exceptions + external IRQs).
pub mod vector_table;

// IVT table (256-byte header at FLASH start, MagicNumber = 0x55AA55AA).
pub mod ivt_table;

// =====================================================================
// Reset_Handler
//
// The hardware enters here out of reset with SP already loaded from
// VECTOR_TABLE[0]. We then:
//   1. disable global interrupts,
//   2. copy ramcode (memcpy64 + memset64) from FLASH (LMA) to ITCM (VMA),
//   3. call main.
// =====================================================================
#[no_mangle]
#[link_section = ".text.Reset_Handler"]
pub unsafe extern "C" fn Reset_Handler() -> ! {
    // (1) Disable global interrupts (cortex_m::interrupt::disable == cpsid i).
    //     No inline asm in user code; the asm is encapsulated in the crate.
    interrupt::disable();

    // (2) Copy ramcode (memcpy64 + memset64) from FLASH load address to ITCM link address.
    extern "C" {
        static __ramcode_start: u8;
        static __ramcode_end: u8;
        static __ramcode_load: u8;
    }
    let src: *const u8 = ptr::addr_of!(__ramcode_load);
    let dst: *mut u8 = ptr::addr_of!(__ramcode_start) as *mut u8;
    let len: usize =
        ptr::addr_of!(__ramcode_end) as usize - ptr::addr_of!(__ramcode_start) as usize;

    // Call memcpy64 via a black_box'd function pointer to prevent LLVM
    // from recognising it as the memcpy builtin and optimising away the call.
    let do_copy: unsafe extern "C" fn(*const u8, *mut u8, usize) -> *mut u8 =
        core::hint::black_box(memcpy64);
    do_copy(src, dst, len);

    // (3) Call main.
    main();
}

// =====================================================================
// memcpy64 -- self-implemented 8-byte aligned block copy.
//
// Parameter order (per spec): (src, dst, n)
//   src : 起始地址 (start / source address)
//   dst : 目标地址 (target / destination address)
//   n   : 字节数长度 (byte count, must be a multiple of 8)
//
// Caller guarantees src and dst are 8-byte aligned.
//
// Returns dst.
// =====================================================================
#[no_mangle]
#[link_section = ".ramcode"]
#[inline(never)]
pub unsafe extern "C" fn memcpy64(src: *const u8, dst: *mut u8, n: usize) -> *mut u8 {
    let count = n / 8;
    let mut i: usize = 0;
    while i < count {
        let offset = i * 8;
        let s = (src as usize + offset) as *const u64;
        let d = (dst as usize + offset) as *mut u64;
        let val = ptr::read_volatile(s);
        ptr::write_volatile(d, val);
        i += 1;
    }
    dst
}

// =====================================================================
// memset64 -- 8-byte aligned memory fill with a u64 value.
//
// Parameter order (per spec): (dst, value, n)
//   dst   : target address (must be 8-byte aligned)
//   value : u64 fill value
//   n     : byte count (must be a multiple of 8)
//
// Returns dst.
// =====================================================================
#[no_mangle]
#[link_section = ".ramcode"]
#[inline(never)]
pub unsafe extern "C" fn memset64(dst: *mut u8, value: u64, n: usize) -> *mut u8 {
    let count = n / 8;
    let mut i: usize = 0;
    while i < count {
        let offset = i * 8;
        let d = (dst as usize + offset) as *mut u64;
        ptr::write_volatile(d, value);
        i += 1;
    }
    dst
}

// =====================================================================
// Default_Handler -- default interrupt handler (infinite loop).
// All undefined interrupt handlers are weak aliases (via PROVIDE in
// link.x) of this function.  A strong definition of any handler
// elsewhere overrides the PROVIDE.
// =====================================================================
#[no_mangle]
#[link_section = ".text.Default_Handler"]
pub extern "C" fn Default_Handler() -> ! {
    loop {}
}

// =====================================================================
// main -- an empty infinite loop.
// =====================================================================
#[no_mangle]
#[inline(never)]
pub extern "C" fn main() -> ! {
    loop {}
}

// =====================================================================
// Panic handler -- just spin.
// =====================================================================
#[panic_handler]
fn panic(_info: &PanicInfo) -> ! {
    loop {}
}
